#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx commitlint --edit "$1"
STATUS=$?

if [ $STATUS -eq 0 ]; then
  echo "✅ Hook commit-msg passou!"
else
  echo "❌ Commit bloqueado pelo commitlint!"
fi

exit $STATUS
