#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged
STATUS=$?

if [ $STATUS -eq 0 ]; then
  echo "✅ Hook pre-commit executado!"
else
  echo "❌ Erros no pre-commit, commit abortado."
fi

exit $STATUS
